Add liveness
MapColonies/shared-images-old pull request #26
Opened 2022-11-20 08:24 UTC by netanelC

Add liveness to nginx-s3-gateway

2022-11-20 08:43 UTC, asafMasa requested changes

2022-11-20 08:43 UTC, asafMasa commented on nginx-s3-gateway/default.conf.template
> +        add_header Content-Type application/json;
use this https://serverfault.com/questions/874144/how-to-turn-off-access-log-for-only-a-certain-url-in-this-nginx-configuration in order to disable the liveness logs
```
access_log    off;
log_not_found off;
```

2022-11-23 08:19 UTC, RonitKissis approved these changes

2022-11-23 15:18 UTC, EllaMartirosyan approved these changes

2022-11-27 09:24 UTC, asafMasa approved these changes

2022-11-27 09:25 UTC, merged