feat(postgresq-osmdbt): created
MapColonies/shared-images-old pull request #27
Opened 2023-01-05 09:49 UTC by CptSchnitz

2023-01-05 10:21 UTC, asafMasa commented
Should this image be in "shared-images" repo?

2023-01-05 11:16 UTC, syncush commented
> Should this image be in "shared-images" repo?

Yes.

2023-01-05 11:19 UTC, syncush requested changes

2023-01-05 11:19 UTC, syncush commented on postgresql-osmdbt/Dockerfile
> +RUN git clone https://github.com/openstreetmap/osmdbt.git &&  \
I think we need to checkout here with a specific version

2023-01-05 11:19 UTC, syncush commented on postgresql-osmdbt/README.md
> +In order to deploy the image on Openshift you should use the [bitnami/postgresql](https://github.com/bitnami/charts/tree/main/bitnami/postgresql) helm chart with the modifications present in the `val
let's add a section that if a programmer wants to change value or add a value, he should look up the helm chart first of bitnami before adding it here.

2023-01-05 11:44 UTC, CptSchnitz commented on postgresql-osmdbt/Dockerfile
> +RUN git clone https://github.com/openstreetmap/osmdbt.git &&  \
done

2023-01-05 11:44 UTC, CptSchnitz commented on postgresql-osmdbt/README.md
> +In order to deploy the image on Openshift you should use the [bitnami/postgresql](https://github.com/bitnami/charts/tree/main/bitnami/postgresql) helm chart with the modifications present in the `val
done

2023-01-08 09:17 UTC, syncush approved these changes

2023-01-08 09:22 UTC, merged