feat: qgis server
MapColonies/shared-images-old pull request #31
Opened 2023-03-09 06:10 UTC by EllaMartirosyan

2023-03-09 07:42 UTC, syncush requested changes

2023-03-09 07:42 UTC, syncush commented on qgis-server/Dockerfile
> +FROM openquake/qgis-server:ltr
Please stick to a specific version `openquake/qgis-server:3.16.13`

2023-03-09 07:42 UTC, syncush commented on qgis-server/Dockerfile
> +# USER nginx
why is it in the comment?

2023-03-09 07:42 UTC, syncush commented on qgis-server/README.md
> +docker build -t <prefix>/qgis-server:v1.0.0 .
```suggestion
docker build -t qgis-server:latest .
```

2023-03-09 07:42 UTC, syncush commented on qgis-server/README.md
> +
if you don't specify the "Why?" 
then don't leave it.

2023-03-09 07:42 UTC, syncush commented on qgis-server/entrypoint.sh
> +exec "$@"
what is the purpose of this script ?
it does nothing

2023-03-13 12:29 UTC, syncush requested changes

2023-03-13 12:29 UTC, syncush commented on qgis-server/Dockerfile
> +ENV ZX_VERSION=1.2.2
it is an ARG, not an ENV.

https://docs.docker.com/engine/reference/builder/#arg

2023-03-13 12:29 UTC, syncush commented on qgis-server/Dockerfile
>      npm
should be a one liner

2023-03-13 12:29 UTC, syncush commented on qgis-server/Dockerfile
>      nodejs \
you should install nodejs like they recommend to do so 

https://github.com/nodesource/distributions

stick to a specific node version. also nodejs comes with npm, you don't need install npm

2023-03-13 12:29 UTC, syncush commented on qgis-server/Dockerfile
>  RUN ./aws/install && aws --version
why do you need to run aws --version ?

2023-03-13 12:29 UTC, syncush commented on qgis-server/Dockerfile
> +ENV AWS_BUCKET_NAME=${aws_bucket_name}
the sdk installation should be before running npm install commands

2023-03-13 12:29 UTC, syncush commented on qgis-server/README.md
> +      --build-arg aws_bucket_name=dem-int \
why is it a build ARG and not ENV? 

this means we need to build 3 qgis servers images each for 
raster, vector and dem

2023-03-13 12:29 UTC, syncush commented on qgis-server/README.md
> +      -e SKIP_NGINX=0 \
what does it mean?

2023-03-13 12:29 UTC, syncush commented on qgis-server/copy-projects.mjs
this shouldn't be done in build time, this needs to be an init container. you can geo-server sidecar for the same type of workflow

2023-03-13 14:09 UTC, alebinson commented on qgis-server/copy-projects.mjs
I agree, it will be changed in further steps... Currently it's good enough for presented scenarios and project milestones

2023-03-14 08:02 UTC, syncush commented on qgis-server/copy-projects.mjs
I strongly disagree, I will not accept it as part of  `shared-images`

While taking a deeper look I see QGIS can save projects to PG. I encourage you to explore this option as it far more stable and reliable than object storage.

2023-03-21 11:12 UTC, syncush requested changes

2023-03-21 11:12 UTC, syncush commented on qgis-server/nginx.conf
> +    worker_connections 1024;
why did you decide on 1024?

2023-03-21 11:12 UTC, syncush commented on qgis-server/nginx.conf
> +    access_log  /dev/stdout;
we should adapt to OpenTelemetry logs format, @CptSchnitz has done it

2023-03-21 11:12 UTC, syncush commented on qgis-server/nginx.conf
> +# -*- coding: utf-8 -*-
We should introduce a limitation on the num of processes NGINX can open at startup

2023-03-21 11:12 UTC, syncush commented on qgis-server/nginx.conf
> +    keepalive_timeout   65;
why did you decide on 65?

2023-03-21 11:12 UTC, syncush commented on qgis-server/nginx.conf
> +    }
why does qgis nginx handles HTTPS?

2023-03-21 11:12 UTC, syncush commented on qgis-server/nginx.conf
> +worker_processes auto;
this is bad, in many clusters we have machines with a massive number of CPUs but a limitation on the number of processes in a single POD, please set it to a fixed number

it is preferable that all nginx configurations are configurable. You can use the helm templating for your advantage

2023-04-13 08:41 UTC, syncush requested changes

2023-04-13 08:41 UTC, syncush commented on qgis-server/README.md
> +      -e AWS_ENDPOINT_URL=http://10.8.0.9:9000 \
values are too specific for mapcolonies, change them to dummy values.

2023-04-13 08:41 UTC, syncush commented on qgis-server/README.md
> +      -e RAW_DATA_PROXY_URL=https://client-int-qgis-integration-nginx-s3-gateway-route-integration.apps.j1lk3njp.eastus.aroapp.io \
same

2023-04-13 10:18 UTC, syncush approved these changes

2023-04-13 10:19 UTC, merged