fix: support custom headers
MapColonies/shared-images-old pull request #33
Opened 2023-06-27 19:58 UTC by EllaMartirosyan

2023-06-29 16:24 UTC, alebinson approved these changes
gr8!

2023-07-02 17:13 UTC, syncush requested changes

2023-07-02 17:13 UTC, syncush commented on nginx-s3-gateway/default.conf.template
> +    proxy_hide_header Content-Encoding;
wait this is hard-coded for all users who would like to use this image, I don't think it is relevant to 3D team. 
we need a templating engine, we should introduce one such that we will support all teams accordingly

2023-07-02 17:13 UTC, syncush commented on nginx-s3-gateway/default.conf.template
> +        stub_status;
what is the problem with return 200 '{"status": "UP"}' ?

if we would like to expose such info we should put it under /status / /metrics in the appropriate format.

But this is should be discussed internally before implemented here.

2023-07-02 20:01 UTC, EllaMartirosyan commented on nginx-s3-gateway/default.conf.template
> +        stub_status;
Ofer told me to use this (exactly like they do in Vector) instead of a hard-coded string that represents a meaningless json...

**stub_status** returns a (very small) predefined status json:

**Active connections: 1 
server accepts handled requests
 3 3 2 
Reading: 0 Writing: 1 Waiting: 0** 

Anyway, we don't check/care about the content of the returned json and as long as they are both small - it doesn't matter which one to use.

2023-07-02 20:31 UTC, EllaMartirosyan commented on nginx-s3-gateway/default.conf.template
> +    proxy_hide_header Content-Encoding;
It was default hard-coded to 8080 in this image (please see Dockerfile) since the first day I created it for 3D (good old days...) and no one overrides this internal port, not 3d, nor dem.

I made up this line back in the days that I did not know docker good enough. It did not come from the original nginx-s3-gateway image which nginx team created and published in github.

In all the examples on the internet (including here in **shared-images/nginx**) - it should be like this:
**RUN sed -i.bak 's/listen\(.*\)80;/listen 8080;/' /etc/nginx/conf.d/default.conf
EXPOSE 8080**

I can't seem to find even one good reason why would someone ever want to change the internal port (which is inside the container) for this nginx image.

2023-07-03 12:36 UTC, syncush commented on nginx-s3-gateway/default.conf.template
> +    proxy_hide_header Content-Encoding;
I wasnt talking about the port 8080 at all, my comment is on `proxy_hide_header Content-Encoding`

2023-07-03 12:37 UTC, syncush commented on nginx-s3-gateway/default.conf.template
> +        stub_status;
I will check on Vector team but 
```
Active connections: 1
server accepts handled requests
3 3 2
Reading: 0 Writing: 1 Waiting: 0
```

is not JSON but a string

2023-07-06 05:27 UTC, asafMasa commented on nginx-s3-gateway/default.conf.template
> +        return 200;
disable logs ? (same as in liveness)

2023-07-06 05:27 UTC, asafMasa commented on nginx-s3-gateway/jwt.js
> +function jwt_payload_sub(r) {
pay attention to check your resources after this change is deployed as it uses a lot of memory

2023-07-06 05:27 UTC, asafMasa commented on nginx-s3-gateway/nginx.conf.template
> +    log_format main escape=json
consider using raster nginx log template to unify our log output

2023-07-06 09:15 UTC, syncush commented on nginx-s3-gateway/nginx.conf.template
> +    log_format main escape=json
Stick to open telemetry format

2023-07-10 08:02 UTC, EllaMartirosyan commented on nginx-s3-gateway/default.conf.template
> +    proxy_hide_header Content-Encoding;
Fixed

2023-07-12 12:59 UTC, syncush requested changes

2023-07-12 12:59 UTC, syncush commented on nginx-s3-gateway/log_format.conf
> +log_format main escape=json
it is still not according to OTEL log spec.

2023-07-13 11:17 UTC, syncush requested changes
Where is the log format?

You've deleted it but haven't implemented it

2023-07-13 19:36 UTC, EllaMartirosyan commented on nginx-s3-gateway/default.conf.template
> +        return 200;
Fixed

2023-07-13 19:39 UTC, EllaMartirosyan commented
Log format moved to helm chart, see nginx-s3-gateway-helm

2023-07-18 18:36 UTC, syncush approved these changes

2023-07-19 08:14 UTC, merged