chore: add chart
MapColonies/shared-images-old pull request #37
Opened 2023-08-15 06:40 UTC by AnguIar

2023-08-15 09:03 UTC, shimoncohen requested changes

2023-08-15 09:03 UTC, shimoncohen commented on nginx/docker-image/nginx-config/status_site.conf
> +}
Add a line at the end of the file.

2023-08-15 09:03 UTC, shimoncohen commented on nginx/docker-image/subset.sh
> +cat /otel/otel-nginx-template.toml | envsubst > /otel/otel-nginx.toml
Add a line at the end of the file.

2023-08-15 09:03 UTC, shimoncohen commented on nginx/helm/templates/route.yaml
> +{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
Please move to begining of file.

2023-08-15 09:03 UTC, shimoncohen commented on nginx/helm/config/log_format.conf
> +        '"mapcolonies.http.auth.token.client_name":"$jwt_payload_sub",'
Please come back with explenation about this and check about the differences between `Attributes` and `Resource`.

2023-08-15 09:03 UTC, shimoncohen commented on nginx/docker-image/README.md
> +All the permissions were changed so a user under the group `root` can run the container.
Please update README.

2023-08-15 13:48 UTC, AnguIar commented on nginx/helm/templates/route.yaml
> +{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
In line 5 there's a condition that checks value of `$cloudProviderFlavor` which is defined couple of lines before, so we need the `if` statement in here.

2023-08-17 11:26 UTC, shimoncohen commented on nginx/README.md
> +There is also an Helm Chart for deploying this Nginx in an Openshift environment (let alone any K8S environment).
Additionaly there is a Helm Chart...

2023-08-17 11:27 UTC, shimoncohen commented on nginx/README.md
> +We are using `nginxinc/nginx-unprivileged` as a base image in order to run Nginx with non-root privileges so it's possible to run in it an Openshift cluster (as we know, Openshift does not allow runn
... to run it in an ...

2023-08-17 11:27 UTC, shimoncohen commented on nginx/README.md
> +Besides that the `Dockerfile` is pretty straight forward so you can open it up and view it by yourself.
... so you can check it out yourself.

2023-08-17 11:31 UTC, shimoncohen commented on nginx/README.md
> +* The docker image does contains the `auth.js` file, which is responsible for handling requests that require authorization **but** the Nginx server does not actually make the authorization process -
The docker image contains ... does not actually handle the ... commented the code section responsible for this logic.

2023-08-17 11:32 UTC, shimoncohen commented on nginx/.gitignore
> +*.tgz
Does this need to be added?

2023-08-17 11:34 UTC, shimoncohen requested changes

2023-08-17 11:34 UTC, shimoncohen commented on nginx/README.md
> +We are using `nginxinc/nginx-unprivileged` as a base image in order to run Nginx with non-root privileges so it's possible to run in it an Openshift cluster (as we know, Openshift does not allow runn
... to run it in an ...

2023-08-20 06:35 UTC, shimoncohen approved these changes

2023-08-20 06:35 UTC, shimoncohen commented on nginx/helm/templates/deployment.yaml
> +          livenessProbe:
Please add a warining.

2023-08-20 06:35 UTC, shimoncohen commented on nginx/helm/values.yaml
> +    prometheus.io/port: '9113'
Please move to `Helpers`.

2023-08-20 07:51 UTC, shimoncohen commented on nginx/helm/templates/route.yaml
> +{{- if and (and (.Values.enabled) (eq $cloudProviderFlavor "openshift")) (.Values.route.enabled) -}}
👍🏻

2023-08-21 14:59 UTC, merged