feat: add redis to nginx-s3-gateway
MapColonies/shared-images-old pull request #46
Opened 2023-11-29 14:58 UTC by netanelC

2023-12-06 07:01 UTC, CptSchnitz requested changes
Great job!
Please change the docs to focus less on redis and still on s3-gateway.
In addition i think adding a working e2e example would be great, we can talk about it.

2023-12-06 07:01 UTC, CptSchnitz commented on nginx-s3-gateway/Dockerfile
> +## ADD-ONS THAT DOES NOT NEED COMPLIATION
```suggestion
## ADD-ONS THAT DOES NOT NEED COMPILATION
```

2023-12-06 07:01 UTC, CptSchnitz commented on nginx-s3-gateway/Dockerfile
> +RUN wget https://openresty.org/download/nginx-1.25.3.tar.gz \
Use [ARG](https://docs.docker.com/engine/reference/builder/#arg) to set the nginx version.

2023-12-06 07:01 UTC, CptSchnitz commented on nginx-s3-gateway/Dockerfile
> +FROM debian as BUILDER
Specify a tag for debian instead of latest

2023-12-06 07:01 UTC, CptSchnitz commented on nginx-s3-gateway/Dockerfile
> +USER nginx
new line missing

2023-12-06 07:01 UTC, CptSchnitz commented on nginx-s3-gateway/README.md
> +# NGINX-S3-Gateway with Redis Feature
```suggestion
# NGINX-S3-Gateway with Lua and Redis Feature
```

2023-12-06 07:01 UTC, CptSchnitz commented on nginx-s3-gateway/README.md
> +   - A working directory named "work" is created to organize and execute the build process.
No need to specify this.
Remove all the stuff that are obvious from just reading the dockerfile.
Stuff like ENV / the nginx build params and what is actually being moved is more important.

2023-12-06 07:01 UTC, CptSchnitz commented on nginx-s3-gateway/README.md
> +   -e REDIS_AUTH=bla \
As the PR doesn't include this now its not needed. same with the redis in the name of the image.

2023-12-07 14:36 UTC, CptSchnitz requested changes

2023-12-07 14:36 UTC, CptSchnitz commented on nginx-s3-gateway/example/docker-compose.yml
> +      - REDIS_READ_TIMEOUT=1000
move env to env-file

2023-12-07 14:36 UTC, CptSchnitz commented on nginx-s3-gateway/README.md
> +**## Example Deployment with Docker Compose**
1. this looks dafuk and metumtam
2. move this to a separate readme inside the example folder

2023-12-10 08:47 UTC, netanelC commented on nginx-s3-gateway/README.md
> +**## Example Deployment with Docker Compose**
Done

2023-12-10 09:57 UTC, shimoncohen requested changes

2023-12-10 09:57 UTC, shimoncohen commented on nginx-s3-gateway/Dockerfile
> +## ADD-ONS THAT DOES NOT NEED COMPILATION
`DOES` -> `DO`.

2023-12-10 09:57 UTC, shimoncohen commented on nginx-s3-gateway/README.md
> +   To determine the appropriate configuration for building NGINX with additional Lua and dynamic modules, I retrieved the configuration command using "nginx -V" within the desired version of NGINX. T
`I` -> `we`.

2023-12-10 09:57 UTC, shimoncohen commented on nginx-s3-gateway/example/21-envsubst-on-nginx-conf.sh
> +envsubst '${NGINX_WORKER_PROCESSES}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
Please add a line at the end of the file.

2023-12-10 09:57 UTC, shimoncohen commented on nginx-s3-gateway/example/docker-compose.yml
> +      /usr/bin/mc alias set myminio http://minio:9000 s3-user s3-password;
Share user and password with `environment` values.

2023-12-10 09:57 UTC, shimoncohen commented on nginx-s3-gateway/example/redis-get-key.lua
> +ngx.print(data)
Please add a line at the end of the file.

2023-12-10 09:57 UTC, shimoncohen commented on nginx-s3-gateway/example/redis-set-key.lua
> +ngx.print(data)
Please add a line at the end of the file.

2023-12-10 09:57 UTC, shimoncohen commented on nginx-s3-gateway/example/nginx.conf
> +}
Please add a line at the end of the file.

2023-12-10 09:57 UTC, shimoncohen commented on nginx-s3-gateway/example/default.conf
> +}
Please add a line at the end of the file.

2023-12-10 11:53 UTC, syncush requested changes

2023-12-10 11:53 UTC, syncush commented on nginx-s3-gateway/README.md
> +   To determine the appropriate configuration for building NGINX with additional Lua and dynamic modules, I retrieved the configuration command using "nginx -V" within the desired version of NGINX. T
WE approve

2023-12-10 11:53 UTC, syncush commented on nginx-s3-gateway/example/21-envsubst-on-nginx-conf.sh
> +envsubst '${NGINX_WORKER_PROCESSES}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
I would add parentheses to improve readability.

2023-12-10 11:53 UTC, syncush commented on nginx-s3-gateway/example/README.md
> +In the `examples` folder, you'll find a Docker Compose file (`docker-compose.yml`) along with NGINX configuration files (`nginx.conf` and `default.conf`) and redis configuration files (key handling f
```suggestion
In the `example` folder, you'll find a Docker Compose file (`docker-compose.yml`) along with NGINX configuration files (`nginx.conf` and `default.conf`) and redis configuration files (key handling files). This example demonstrates a simplified deployment of NGINX-S3-Gateway with Redis integration.
```

2023-12-10 11:53 UTC, syncush commented on nginx-s3-gateway/example/minioData/bla.txt
> +BLA
don't call it "bla", "example" would be more proper.

2023-12-10 11:53 UTC, syncush commented on nginx-s3-gateway/example/nginx.conf
> +load_module modules/ngx_http_headers_more_filter_module.so;
add a comment about those modules needed for redis.

2023-12-10 11:53 UTC, syncush commented on nginx-s3-gateway/example/redis-get-key.lua
> +red:set_keepalive(os.getenv("REDIS_MAX_IDLE_TIMEOUT"), os.getenv("REDIS_POOL_SIZE"))
extract env values into variables

2023-12-10 11:53 UTC, syncush commented on nginx-s3-gateway/example/redis-set-key.lua
> +local ok, err = red:connect(os.getenv("REDIS_HOST"), os.getenv("REDIS_PORT"))
extract env

2023-12-10 11:53 UTC, syncush commented on nginx-s3-gateway/example/redis-set-key.lua
> +    ngx.log(ngx.ERR, "Didn't managed to set key, error -> ", err)
```suggestion
    ngx.log(ngx.ERR, "failed to set key, error -> ", err)
```

2023-12-10 11:59 UTC, shimoncohen commented on nginx-s3-gateway/example/minioData/bla.txt
> +BLA
Seconded.

2023-12-11 06:58 UTC, netanelC commented on nginx-s3-gateway/Dockerfile
> +## ADD-ONS THAT DOES NOT NEED COMPILATION
Done

2023-12-11 06:58 UTC, netanelC commented on nginx-s3-gateway/Dockerfile
> +## ADD-ONS THAT DOES NOT NEED COMPILATION
DO

2023-12-11 06:59 UTC, netanelC commented on nginx-s3-gateway/README.md
> +   To determine the appropriate configuration for building NGINX with additional Lua and dynamic modules, I retrieved the configuration command using "nginx -V" within the desired version of NGINX. T
Done

2023-12-11 07:00 UTC, netanelC commented on nginx-s3-gateway/example/21-envsubst-on-nginx-conf.sh
> +envsubst '${NGINX_WORKER_PROCESSES}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
Done

2023-12-11 12:57 UTC, netanelC commented on nginx-s3-gateway/example/redis-get-key.lua
> +ngx.print(data)
Done

2023-12-11 13:12 UTC, netanelC commented on nginx-s3-gateway/example/redis-set-key.lua
> +ngx.print(data)
Done

2023-12-11 13:12 UTC, netanelC commented on nginx-s3-gateway/example/redis-set-key.lua
> +    ngx.log(ngx.ERR, "Didn't managed to set key, error -> ", err)
Done

2023-12-11 13:17 UTC, netanelC commented on nginx-s3-gateway/example/redis-get-key.lua
> +red:set_keepalive(os.getenv("REDIS_MAX_IDLE_TIMEOUT"), os.getenv("REDIS_POOL_SIZE"))
Done

2023-12-11 13:19 UTC, netanelC commented on nginx-s3-gateway/example/redis-set-key.lua
> +local ok, err = red:connect(os.getenv("REDIS_HOST"), os.getenv("REDIS_PORT"))
Done

2023-12-11 13:22 UTC, netanelC commented on nginx-s3-gateway/example/README.md
> +In the `examples` folder, you'll find a Docker Compose file (`docker-compose.yml`) along with NGINX configuration files (`nginx.conf` and `default.conf`) and redis configuration files (key handling f
Done

2023-12-11 13:28 UTC, netanelC commented on nginx-s3-gateway/example/nginx.conf
> +load_module modules/ngx_http_headers_more_filter_module.so;
Done

2023-12-11 13:35 UTC, netanelC commented on nginx-s3-gateway/example/minioData/bla.txt
> +BLA
Done

2023-12-11 13:36 UTC, netanelC commented on nginx-s3-gateway/example/nginx.conf
> +}
Done

2023-12-11 13:36 UTC, netanelC commented on nginx-s3-gateway/example/default.conf
> +}
Done

2023-12-11 13:36 UTC, netanelC commented on nginx-s3-gateway/example/default.conf
> +}
Done

2023-12-11 14:15 UTC, netanelC commented on nginx-s3-gateway/example/21-envsubst-on-nginx-conf.sh
> +envsubst '${NGINX_WORKER_PROCESSES}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf
This is the syntax from nginx itself. Isn't it better to keep it as it is?

2023-12-13 11:03 UTC, syncush approved these changes

2023-12-13 18:31 UTC, shimoncohen approved these changes

2023-12-13 18:31 UTC, shimoncohen commented on nginx-s3-gateway/example/.env
> +REDIS_PASSWORD="redis-password"
Please add a line at the end of the file.

2023-12-27 12:44 UTC, netanelC commented on nginx-s3-gateway/example/.env
> +REDIS_PASSWORD="redis-password"
Done

2023-12-27 14:08 UTC, AnguIar requested changes

2023-12-27 14:08 UTC, AnguIar commented on nginx-s3-gateway/README.md
> +To run a container based on the newly created image:
`To run a container` should be enough here

2023-12-27 14:47 UTC, netanelC commented on nginx-s3-gateway/README.md
> +To run a container based on the newly created image:
Done

2023-12-27 14:51 UTC, AnguIar approved these changes

2023-12-28 15:26 UTC, syncush approved these changes

2023-12-31 11:44 UTC, CptSchnitz approved these changes

2023-12-31 12:04 UTC, merged