feat: add redis user and ssl
MapColonies/shared-images-old pull request #50
Opened 2024-01-04 18:11 UTC by netanelC

2024-01-09 11:59 UTC, syncush requested changes

2024-01-09 11:59 UTC, syncush commented on nginx-s3-gateway/example/.env
> +REDIS_SSL_ENABLED=false
if we enable SSL, how do we provide a certificate or public key ?

2024-01-10 07:46 UTC, netanelC commented on nginx-s3-gateway/example/.env
> +REDIS_SSL_ENABLED=false
At this point, we don't. This is for enabling TLS connection without providing the certificates directly

2024-01-10 07:56 UTC, syncush commented on nginx-s3-gateway/example/.env
> +REDIS_SSL_ENABLED=false
then SSL should be always false without a parameter since we dont support `REDIS_SSL_ENABLED=true`

2024-01-11 09:50 UTC, netanelC commented on nginx-s3-gateway/example/.env
> +REDIS_SSL_ENABLED=false
We can support TLS connection without providing the certs if there is a third-party that provides the certs. In that case, all we need is to enable the SSL connection

2024-01-11 13:01 UTC, syncush approved these changes

2024-01-14 22:09 UTC, shimoncohen commented on nginx-s3-gateway/example/.env
> +REDIS_SSL_ENABLED=false
You should still allow to provide the certs if wanted.

2024-01-14 22:09 UTC, shimoncohen approved these changes

2024-01-16 17:53 UTC, merged