chore: auto ingress host
MapColonies/shared-images-old pull request #53
Opened 2024-02-20 14:06 UTC by almog8k

1. Adding Ingress.domain under global to values.yaml 
2. changing host name value based on releaseName-chartName-IngressDomain

2024-02-21 09:48 UTC, AnguIar commented on nginx/helm/templates/_helpers.tpl
> +{{- end -}}
Add new line

2024-02-21 10:02 UTC, AnguIar commented on nginx/helm/templates/_helpers.tpl
> +{{- printf "%s-%s.%s" .Release.Name .Chart.Name .Values.global.ingress.domain | indent 1 }}
`.Release.Name .Chart.Name` might cause duplication with multiple nginx-subcharts in the same umbrella.
Use `nginx.fullname` instead.

2024-02-21 10:03 UTC, AnguIar requested changes
Good job :)

2024-02-21 12:06 UTC, almog8k commented on nginx/helm/templates/_helpers.tpl
> +{{- end -}}
line added

2024-02-21 12:06 UTC, almog8k commented on nginx/helm/templates/_helpers.tpl
> +{{- printf "%s-%s.%s" .Release.Name .Chart.Name .Values.global.ingress.domain | indent 1 }}
done!

2024-02-21 13:04 UTC, michalby24 approved these changes

2024-02-21 18:13 UTC, AnguIar commented on nginx/helm/templates/_helpers.tpl
> +{{- printf "%s.%s" $ingressFullname .Values.global.ingress.domain | indent 1 }}
`indent 1`?

2024-02-22 08:28 UTC, AnguIar approved these changes

2024-02-22 08:28 UTC, AnguIar commented
Nice work :)

2024-02-22 08:28 UTC, merged